name: Client archiving
on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 10,22 * * 1,2,3,4,5' # 10AM, 10PM CST
      timezone: 'Asia/Taipei'
  workflow_dispatch:

concurrency:
  group: client-archiving
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v7

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        package-manager-cache: false

    - name: Setup pnpm
      uses: pnpm/action-setup@v6
      with:
        version: 11.8.0
        cache: true
        run_install: false

    - name: Install dependencies
      run: pnpm i --frozen-lockfile

    - name: Check patch info
      id: check
      run: pnpm check
      env:
        TCG_SERVER_ENDPOINT: ${{ secrets.TCG_SERVER_ENDPOINT }}

    - name: Restore or ping cached full client zips
      uses: actions/cache/restore@v5
      with:
        key: full-client-${{ github.run_id }}
        restore-keys: |
          full-client-
        path: cache
        lookup-only: ${{ steps.check.outputs.endpoint == '' }}

    - name: Extract cached full client zips to client
      if: ${{ steps.check.outputs.endpoint != '' }}
      run: pnpm restore-cache

    - name: Start client archiving
      id: archive
      if: ${{ steps.check.outputs.endpoint != '' }}
      run: |
        pnpm archive `
        --endpoint=${{ steps.check.outputs.endpoint }} `
        --id=${{ steps.check.outputs.id }} `
        --version=${{ steps.check.outputs.version }} `
        --mode=${{ steps.check.outputs.mode }}

    - name: Save full client to cache
      if: ${{ steps.check.outputs.endpoint != '' && steps.archive.outputs.noClientCache != 'true' && steps.archive.outputs.noFullClientCache != 'true'}}
      uses: actions/cache/save@v5
      with:
        key: full-client-${{ github.run_id }}
        path: cache

    - name: Commit meta.json and create a new tag
      if: ${{ steps.check.outputs.endpoint != '' }}
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        branch: main
        commit_message: 'chore: update meta.json'
        file_pattern: meta.json
        tagging_message: 'P${{ steps.check.outputs.version }}'

    - name: Expose current date
      if: ${{ steps.check.outputs.endpoint != '' }}
      uses: Kaven-Universe/github-action-current-date-time@v1
      id: date
      with:
        format: 'YYYY-MM-DD'

    - name: Create release note
      if: ${{ steps.check.outputs.endpoint != '' }}
      run: |
        $addedCount = [int]"${{ steps.archive.outputs.addedCount || '0' }}"
        $updatedCount = [int]"${{ steps.archive.outputs.updatedCount || '0' }}"
        $removedCount = [int]"${{ steps.archive.outputs.removedCount || '0' }}"
        $sizeChanged = "${{ steps.archive.outputs.sizeChanged || '+0 MB' }}"

        $releaseNote = @(
          "## Archive Info"
          ""
          "Release date: ${{ steps.date.outputs.time }}"
          ""
          "Instructions: https://kinf.cc/Gz6ni"
          ""
          "## Archive Summary"
          ""
          " - $addedCount files added"
          " - $updatedCount files updated"
          " - $removedCount files removed"
          " - Client size $sizeChanged"
        )

        Set-Content -Path 'release-note.md' -Value $releaseNote -Encoding utf8

    - name: Create release
      if: ${{ steps.check.outputs.endpoint != '' }}
      uses: ncipollo/release-action@v1
      with:
        tag: 'P${{ steps.check.outputs.version }}'
        bodyFile: 'release-note.md'
        artifacts: 'archives/*.zip'
        makeLatest: true
