name: Client archiving
on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 4,14 * * 1,2,3,4,5' # 12PM, 10PM CST
  workflow_dispatch:
jobs:
  release:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i
    - name: Restore cached client files
      uses: actions/cache/restore@v4
      with:
        path: client
        key: client
    - name: Start client archiving
      run: pnpm start
      env:
        CLIENT_ARCHIVE_URL: ${{ secrets.CLIENT_ARCHIVE_URL }}
    - name: Save client files to cache
      uses: actions/cache/save@v4
      with:
        path: client
        key: client
    - name: Expose version
      id: meta
      run: |
        $json = Get-Content 'meta.json' | ConvertFrom-Json
        echo "version=$(echo $json.version)" >> $env:GITHUB_OUTPUT
    - name: Commit meta.json and create a new tag
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main
        commit_message: 'chore: update meta.json'
        file_pattern: meta.json
        tagging_message: 'P${{ steps.meta.outputs.version }}'
    - name: Expose current date
      uses: Kaven-Universe/github-action-current-date-time@v1
      id: date
      with:
        format: 'YYYY-MM-DD'
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: 'P${{ steps.meta.outputs.version }}'
        body: 'Release date: ${{ steps.date.outputs.time }}'
        artifacts: 'archives/*.zip'
        makeLatest: true
