name: Client archiving
on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 6,20 * * 1,2,3,4,5'
  workflow_dispatch:
jobs:
  release:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i
    - name: Start client archiving
      run: pnpm start
    - name: Expose meta
      id: meta
      run: |
        content=`cat ./meta.json`
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=metaJson::$content"
    - name: Commit meta.json and create a new tag
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main
        commit_message: 'chore: update meta.json'
        file_pattern: meta.json
        tagging_message: 'P${{ fromJson(steps.meta.outputs.metaJson).version }}'
    - name: Expose current date
      uses: Kaven-Universe/github-action-current-date-time@v1
      id: date
      with:
        format: 'YYYY-MM-DD'
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        body: 'Release date: ${{ steps.date.outputs.time }}'
        artifacts: 'archives/*.zip'
